#!/bin/sh
. "$(dirname "$0")/_/husky.sh"


commit_regex='^Merge.+|(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\(.+\))?: .{1,50}'


if ! grep -iqE "$commit_regex" "$1"; then

echo
echo "commit信息格式错误！！"

echo "格式应为：[Type]: [Summary]"

echo "Type可选值为Merge|feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert"

echo "\033[31mfeat:增加新特性\033[0m"
echo "\033[31mfix:修复 bug\033[0m"
echo "\033[31mdocs:仅仅修改文档\033[0m"
echo "\033[31mstyle:仅仅修改了空格、格式缩进、逗号等等，不改变代码逻辑\033[0m"
echo "\033[31mrefactor:代码重构，没有加新功能或者修复 bug\033[0m"
echo "\033[31mperf:优化相关，比如提升性能、体验\033[0m"
echo "\033[31mbuild:依赖相关的内容\033[0m"
echo "\033[31mci:ci 配置相关 例如对 k8s,docker 的配置文件的修改\033[0m"
echo "\033[31mchore:改变构建流程、或者增加依赖库、工具等\033[0m"
echo "\033[31mrevert:回归到上一个版本\033[0m"

echo "注意中间的空格"

echo "示例：git commit -m \"test: add something test\""

echo
exit 1
fi